FROM node:16

# Set the working directory inside the container
WORKDIR /usr/src/vueproject/frontend

# Copy the rest of your application code to the container
COPY . .

# Change permissions for entrypoint.sh

# Expose the port that your Node.js app is running on
EXPOSE 8083

# Use a shell to run the entrypoint script

# Define the command to start your Node.js application
