version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/vueproject/backend
    env_file: .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    command: ["node", "server.js"]  # Specify the command to start the backend
    depends_on:
      - mongo
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/vueproject/frontend
    ports:
      - "${VUE_PORT}:${VUE_PORT}"
    command: ["npm", "run", "serve"]  # Specify the command to start the frontend
   
  mongo:
    image: mongo
    ports:
      - "${MONGODB_DOCKER}:${MONGODB_DOCKER}"
    volumes:
      - ./data:/data/db

volumes:
  backend: {}
  frontend: {}
  data: {}