services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/vueproject/backend
    env_file: .env
    ports:
      - 8080:8080
    command: ["sh", "-c", "tail -f /dev/null"]
    depends_on:
      - mongo
    
    

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/vueproject/frontend
    ports:
      - 8083:8083
    command: ["sh", "-c", "tail -f /dev/null"]
   
   

  mongo:
    image: mongo
    ports:
      - "27018:27018"
    volumes:
      - ./data:/data/db

volumes:
  backend: {}
  frontend: {}
  data: {}
    