services:
  app:
    build: 
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/vueproject
      - ./frontend:/usr/src/vueproject
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - mongo
   

  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db

volumes:
  backend: {}
  frontend: {}
  data: {}
    