FROM node:16

# Set the working directory inside the container
WORKDIR /usr/src/vueproject/backend

# Copy the rest of your application code to the container
COPY . .

# Expose the port that your Node.js app is running on
EXPOSE 8080

